import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";


import "./globals.css";

const vazir = Vazirmatn({ subsets: ["arabic"] });


export const metadata: Metadata = {
  title: "to do",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.className}>{children}</body>
    </html>
  );
}
